### ISSUE TITLE
[QUESTION] Why Dragonfly is slower than redis on golang stack?

### ISSUE THREAD

**Issue by akuzia** [dragonflydb/dragonfly#81]
Considering dragonfly as drop in replacment for redis on high throughput/low latency caching.
Below is a simple "benchmark" to compare db read/write performance. It Writes sample db with 100k keys, then read them, simulating 10 concurrent clients. So ~100mb of concurrent data traffic in and out.

Results
```
dragonfly-vs-redis-bench-1  | Redis:
dragonfly-vs-redis-bench-1  | Populating db took 1.775606069s
dragonfly-vs-redis-bench-1  | Reading db took 1.6870264s
dragonfly-vs-redis-bench-1  | ====================
dragonfly-vs-redis-bench-1  | Dragonfly:
dragonfly-vs-redis-bench-1  | Populating db took 12.969991441s
dragonfly-vs-redis-bench-1  | Reading db took 12.966059586s
```

Reproduce:

compose
```yml
version: '3'

services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly

  redis:
    image: redis:7

  bench:
    image: golang:1.18
    working_dir: /var/app
    command: ['go', 'run', 'main.go']
    volumes:
      - .:/var/app

```
main.go
```golang
package main

import (
	"encoding/base64"
	"fmt"
	"math/rand"
	"sync"
	"time"

	"github.com/go-redis/redis"
)

func main() {
	fmt.Println("Redis:")
	redisCLient := redis.NewClient(&redis.Options{
		Addr:     "redis:6379",
		Password: "",
		DB:       0,
	})
	benchRedisClient(redisCLient)
	fmt.Println("====================")

	fmt.Println("Dragonfly:")
	dragonflyClient := redis.NewClient(&redis.Options{
		Addr:     "dragonfly:6379",
		Password: "",
		DB:       0,
	})
	benchRedisClient(dragonflyClient)
}

func benchRedisClient(client *redis.Client) {
	startPopulating := time.Now()

	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		go func(i int) {
			for j := 0; j < 10000; j++ {
				token := make([]byte, 1000)
				rand.Read(token)

				val := base64.StdEncoding.EncodeToString(token)
				key := fmt.Sprintf("key%d", i*10000+j)

				client.Set(key, val, 0)
			}
			wg.Done()
		}(i)
		wg.Add(1)
	}
	wg.Wait()
	fmt.Printf("Populating db took %s\n", time.Since(startPopulating))

	startReading := time.Now()
	for i := 0; i < 10; i++ {
		minKey := i * 10000
		maxKey := (i + 1) * 10000

		go func() {
			for i := minKey; i < maxKey; i++ {
				client.Get(fmt.Sprintf("key%d", i))
			}
			wg.Done()
		}()
		wg.Add(1)
	}

	wg.Wait()
	fmt.Printf("Reading db took %s\n", time.Since(startReading))
}
```

Why dragonfly is almost 10 times slower with the same usage scenario? And performance scales almost linearly with number of goroutines:
5 = ~5sec r/w
20 = ~20sec r/w
etc.

**Comment by romange** [comment]
do you run everything locally? what hardware? did you try on cloud?
i will double check it on my machine

**Comment by akuzia** [comment]
Yep, locally. Running on cloud is not on option for us, considering onprem installation.

inxi:
```
CPU:
  Info: 6-core model: AMD Ryzen 5 4600U with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 3 MiB
  Speed (MHz): avg: 3580 min/max: 1400/2100 cores: 1: 3752 2: 3729 3: 3600
    4: 3591 5: 3825 6: 3830 7: 3469 8: 3502 9: 3660 10: 3587 11: 2903 12: 3521
Memory:
  RAM: total: 14.57 GiB used: 8.36 GiB (57.4%)
  Array-1: capacity: 16 GiB slots: 2 EC: None
  Device-1: DIMM 0 type: DDR4 size: 8 GiB speed: 3200 MT/s
  Device-2: DIMM 0 type: DDR4 size: 8 GiB speed: 3200 MT/s
```

**Comment by romange** [comment]
I get 
```
ench_1      | main.go:10:2: no required module provides package github.com/go-redis/redis: go.mod file not found in current directory or any parent directory; see 'go help modules'
build-dbg_bench_1 exited with code 1
```
when running docker compose. 
when trying to build locally I get 
```
# command-line-arguments
./main.go:45:15: not enough arguments in call to client.cmdable.Set
	have (string, string, number)
	want (context.Context, string, interface {}, time.Duration)
./main.go:61:15: not enough arguments in call to client.cmdable.Get
	have (string)
	want (context.Context, string)
```

I prefer building locally.  Can you fix main.go to compile on `go1.17` ?

**Comment by akuzia** [comment]
go.mod
```go
module dragonfly-redis-bench

go 1.17

require (
	github.com/go-redis/redis/v8 v8.11.5
)

require (
	github.com/cespare/xxhash/v2 v2.1.2 // indirect
	github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f // indirect
)

```

main.go
```go
package main

import (
	"context"
	"encoding/base64"
	"fmt"
	"math/rand"
	"sync"
	"time"

	"github.com/go-redis/redis/v8"
)

func main() {
	fmt.Println("Redis:")
	redisCLient := redis.NewClient(&redis.Options{
		Addr:     "redis:6379",
		Password: "",
		DB:       0,
	})
	benchRedisClient(redisCLient)
	fmt.Println("====================")

	fmt.Println("Dragonfly:")
	dragonflyClient := redis.NewClient(&redis.Options{
		Addr:     "dragonfly:6379",
		Password: "",
		DB:       0,
	})
	benchRedisClient(dragonflyClient)
}

func benchRedisClient(client *redis.Client) {
	startPopulating := time.Now()

	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		go func(i int) {
			for j := 0; j < 10000; j++ {
				token := make([]byte, 1000)
				rand.Read(token)

				val := base64.StdEncoding.EncodeToString(token)
				key := fmt.Sprintf("key%d", i*10000+j)

				client.Set(context.Background(), key, val, 0)
			}
			wg.Done()
		}(i)
		wg.Add(1)
	}
	wg.Wait()
	fmt.Printf("Populating db took %s\n", time.Since(startPopulating))

	startReading := time.Now()
	for i := 0; i < 10; i++ {
		minKey := i * 10000
		maxKey := (i + 1) * 10000

		go func() {
			for i := minKey; i < maxKey; i++ {
				client.Get(context.Background(), fmt.Sprintf("key%d", i))
			}
			wg.Done()
		}()
		wg.Add(1)
	}

	wg.Wait()
	fmt.Printf("Reading db took %s\n", time.Since(startReading))
}

```

**Comment by romange** [comment]
I think I have some direction.

I changed the main file to connect to localhost and increased the loop.

I tested both Redis and DF serially without docker compose.
These are my numbers:
### DF
Populating db took 18.142100231s
Reading db took 15.250208999s

### Redis6
Populating db took 22.012566837s
Reading db took 15.925689501s

Looks ok.

however DF with docker:  `docker run -p 6379:6379 dragonfly`
```
Populating db took 39.772936421s
Reading db took 35.586250403s
```
with  `docker run --network=host dragonfly`:
```
Dragonfly:
Populating db took 26.029379714s
Reading db took 20.159797822s
```

Seems that docker network interferes with Dragonfly latency. In any case it was not 10x time slower but twice slower.

Can you check if running DF natively on host solves the performance problem on your machine? 


```go
package main

import (
	"context"
	"encoding/base64"
	"fmt"
	"math/rand"
	"sync"
	"time"

	"github.com/go-redis/redis/v8"
)

func main() {
	/*fmt.Println("Redis:")
	redisCLient := redis.NewClient(&redis.Options{
		Addr:     "redis:6379",
		Password: "",
		DB:       0,
	})
	benchRedisClient(redisCLient)*/
	fmt.Println("====================")

	fmt.Println("Dragonfly:")
	dragonflyClient := redis.NewClient(&redis.Options{
		Addr:     "localhost:6379",
		Password: "",
		DB:       0,
	})
	benchRedisClient(dragonflyClient)
}

func benchRedisClient(client *redis.Client) {
	startPopulating := time.Now()

	var wg sync.WaitGroup
	for i := 0; i < 20; i++ {
		go func(i int) {
			for j := 0; j < 100000; j++ {
				token := make([]byte, 1000)
				rand.Read(token)

				val := base64.StdEncoding.EncodeToString(token)
				key := fmt.Sprintf("key%d", i*100000+j)

				client.Set(context.Background(), key, val, 0)
			}
			wg.Done()
		}(i)
		wg.Add(1)
	}
	wg.Wait()
	fmt.Printf("Populating db took %s\n", time.Since(startPopulating))

	startReading := time.Now()
	for i := 0; i < 20; i++ {
		minKey := i * 100000
		maxKey := (i + 1) * 100000

		go func() {
			for i := minKey; i < maxKey; i++ {
				client.Get(context.Background(), fmt.Sprintf("key%d", i))
			}
			wg.Done()
		}()
		wg.Add(1)
	}

	wg.Wait()
	fmt.Printf("Reading db took %s\n", time.Since(startReading))
}
```

**Comment by akuzia** [comment]
I've ran latest release natively, nothing seems to change:
100k keys (my loop)
```
Dragonfly:
Populating db took 12.200772976s
Reading db took 10.173154839s
```
2mil keys (your loop)
```
Dragonfly:
Populating db took 3m4.011531468s
Reading db took 3m0.691556751s
```

Metrics shown in web UI:
```
request_latency_usec 
GET:count:2558 sum:3114349 average:1217.49
SET:count:3413 sum:4063330 average:1190.54 
```

get_qps & set_qps hover around 10-12k

**Comment by akuzia** [comment]
v0.1.0

**Comment by romange** [comment]
ok, I think it's related to this bug https://github.com/dragonflydb/dragonfly/issues/66


you can either build from source to confirm quickly that this solves your issue , or alternatively I can release a patch release  from HEAD and it will take ~2 hours.

**Comment by romange** [comment]
I started the prerelease pipeline anyway.

**Comment by romange** [comment]
@akuzia  can you please try https://github.com/dragonflydb/dragonfly/releases/tag/v0.1.1 ?

Thanks

**Comment by romange** [comment]
Latency of 1ms server side is really bad.
How your htop  looks like?

**Comment by romange** [comment]
I've googled up your processor - its a laptop. I've tested dragonfly on my
home computer but its mainly intended for high quality systems that exist
on the cloud or data centers.

I suggest that you test it on your on-prem machine and not a laptop. I do
not think its related to golang stack in any way.

**Comment by romange** [comment]
Closing. Feel free to reopen if you have more questions.
